name: misspell

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request: null

jobs:
  misspell:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # pin@v3
      - name: misspell
        uses: reviewdog/action-misspell@811b1e15f531430be3a5784e3d591bd657df18b0 # pin@v1
        with:
          locale: US
