name: misspell

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request: null

jobs:
  misspell:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3
      - name: misspell
        uses: reviewdog/action-misspell@3347037502cd60235723196fe0084fd1c11ff33a # pin@v1
        with:
          locale: US
