name: misspell

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request: null

jobs:
  misspell:
    name: spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # pin@v3
      - name: misspell
        uses: reviewdog/action-misspell@14a9098a2dd70099f1c1b474576d70111d21e424 # pin@v1
        with:
          locale: US
